### ISSUE TITLE
[FE] Guide users to verify their email addresses

### ISSUE THREAD

**Issue by younghyunlee22** [YoungLeeHan/YoungleehanKorean#117]
With the backend code changed in order to make all the users verify their email addresses, we need to guide users on their browsers.

1. Register page
- upon registering, auth-check is called and it results in a 400 error.
- we need to show a message that the verification email has been sent to the user when they click on the 'Create account' button. 
Currently, we navigate them to the login page upon clicking on the 'register' button, but we no longer need to.
After getting verified, they will see a button to navigate to the login page.

2. Login page
- we need to show a message that the verification email has been sent to users when they click on the 'login' button. 

3. After getting verified, they will see a button to navigate to the login page.

Note: 'forgot password' page is expected to work in a similar way.

**Comment by sweetrain05** [comment]
Hi Younghyun, Thanks for input.
Here is how I implemented your suggestions.

**1. Register Page:**
1) auth-check will not be called anymore. Improved the code to use auth.token from local storage instead of making extra API call. (This will be faster, without sacrificing the feature! yay!)
#122 

2) I added a green styled modal to guide the end user about the e-mail verification. When they click 'got it', they will be navigated to '/'. 
![image](https://github.com/YoungLeeHan/YoungleehanKorean/assets/86023470/7c62c474-ac8c-4af4-be4e-ebad4dfa06d6)

I will keep you updated with Login Page when it's done!

**Comment by younghyunlee22** [comment]
I like the modal! Thanks!

**Comment by sweetrain05** [comment]
Hi Younghyun, your request regarding Login Page is implemented as following. 
https://github.com/YoungLeeHan/YoungleehanKorean/pull/134/commits/10dfe8b2fa60b9dbe2d3fe9cb5fb302832500117
#
and for the third inquiry, please look into these commits: 
https://github.com/YoungLeeHan/YoungleehanKorean/commit/4552608f672b239d2f6aa7f14738f4ceb275828e
https://github.com/YoungLeeHan/YoungleehanKorean/pull/135/commits/91316c70c6473b9fabfec39fb1b2923c85980962

**Comment by younghyunlee22** [comment]
Everything looks good. Thank you so much!
