### ISSUE TITLE
[FE] Header fix request

### ISSUE THREAD

**Issue by younghyunlee22** [YoungLeeHan/YoungleehanKorean#123]
Upon clicking on the 'Create account button, it shows 'Hi, {firstName}' in the header even though the user hasn't signed in yet.

**Comment by sweetrain05** [comment]
Hi Younghyun,
Good job on finding the bug!

I fixed it by doing the following:

### **Back-end**
I changed the `register` controller to return just success message instead of user data. 
I figured that we do not need the user data as a response to register action.
(If we do, it will affect the header which takes in `user.firstName` and result in showing the unlogged-in user name)

-Before:
```
res.json({
      user: {
        firstName: user.firstName,
        lastName: user.lastName,
        email: user.email,
        role: user.role,
        _id: user._id,
      },
      token,
    });
```

-After:
```
 res.json({
      registrationStatus: "success",
    });
```

### **Front-end**
In `RegisterForm.js`, upon registering, it used to receive user data from backend(as shown above) and save it in `auth global state`, which is then used on the header to show firstName.
On the front-end, I changed the code to not to set` auth global state` anymore(in fact, there is no data to save anymore since we altered the backend response), and in addition, it now shows a modal that notifies the end user that an e-mail verification was sent to their email address. 

-Before:
```
// actions after successful registration
setAuth({ ...auth, token: data.token, user: data.user });
toast.success(`${data?.user?.firstName} Thank you for joining the club!`);
navigate(`/login`);
```

-After:
```
// actions after successful registration
 setIsModalOpen(true);
```
