### ISSUE TITLE
[BE] abuse of switch?!

### ISSUE THREAD

**Issue by ryuina** [YoungLeeHan/YoungleehanKorean#92]
https://github.com/YoungLeeHan/YoungleehanKorean/blob/a45be186a1c9aa8ebc7252bde0b215c31f6db9b5/server/controllers/product.js#L11-L29

This switch-case is quite weird...?!
Normally, you can use switch-case when a value is different with case like below
```
switch(variable) {
  case "PRIMARY": 
  case "SECONDARY":
  case "ELSE":
  ...
}
```

So in this codes, you use switch-case for just compute each validation cases and return.
Then just use if-else conditions. If-else is default, and switch-case is used specially.

```js
const validateProduct = (product) => {
  if (condition1) {
    return res.json({ 
       error: "Image should be less than 1mb in size", 
     }); 
  }
  if (condition2) {
    return res.json(..);
  }
   ... 
}

export const create = async (req, res) => {
  ...
  validateProduct(product)
  ...
}
```

There's another point on this, you can choose to separate validation function outside of the create logic and simplify the create function.

**Comment by MayHyeyeonKim** [comment]
Hi Ina,

Thanks for bringing this up and for your valuable feedback. You're absolutely right; the switch-case construct in the code you mentioned may appear unusual. Typically, switch-case is used when you have a single variable that you want to compare against multiple values, as you demonstrated in your example with "PRIMARY", "SECONDARY", and "ELSE".

Here's a modified version of your create function using if-else statements and separating the validation logic into a reusable function:

```
  if (!product.title.trim()) {
    return { error: "Title is required" };
   }
  if (product.images && product.images.size > 1000000) {
    return {
      error: "Image should be less than 1MB in size",
    };
  }
  if (!product.category.trim()) {
    return { error: "Category is required" };
  }
  if (!product.ageCategory.trim()) {
    return { error: "Age category is required" };
  }
  if (!product.description.trim()) {
    return { error: "Description is required" };
  }
  if (!product.price.trim()) {
    return { error: "Price is required" };
  }
  if (!product.downloadUrl.trim()) {
    return { error: "DownloadUrl is required" };
  }
  return null;
};
```

However, due to the independent and straightforward nature of the validation conditions for this product, and because a switch statement appeared to offer a more concise logic for validation compared to using if-else, we reached a consensus with our team members to proceed with the switch statement.

we've also improved the code by extracting duplicated functions into a separate 'validateProduct' function within the 'helpers' directory. This has greatly enhanced code readability and reusability.

I appreciate your valuable feedback once again. 👍
